# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/

# Appearance
appearance:
  mode: system
  color: emerald
  theme_day: minimal      # light palette similar to classic
  theme_night: minimal    # optional: keep dark mode consistent
  font: classic           # or 'minimal' — try both
  font_size: m

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: ''
    twitter: ''           # put your @ handle here or leave blank
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: false
    show_theme_chooser: false
    logo:
      text: "Alexandros Gilch"

# Site footer
footer:
  copyright:
    notice: 'Alexandros Gilch - University of Bonn | Last updated: October 2025.'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false

# Load site-specific CSS overrides (files live under assets/css/)
custom_css:
  - assets/css/custom.css
  - css/research.css
